name: novel_glide
version: 1.2.5+58
publish_to: none
environment:
  sdk: ">=3.2.3 <4.0.0"
description: A cross-platform novel reader app.
dependencies:
  accessibility_tools: ^2.2.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dio: ^5.9.0
  epubx: ^4.0.0
  equatable: ^2.0.5
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  file_picker: ^10.1.2
  firebase_analytics: ^12.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_performance: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^4.2.2
  get_it: ^8.1.0
  google_mobile_ads: ^6.0.0
  google_sign_in: ^7.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  html: ^0.15.4
  http: ^1.2.2
  image: ^3.3.0
  intl: any
  loading_animation_widget: ^1.2.0+4
  logger: ^2.4.0
  markdown_widget: ^2.3.2+8
  mime: ^2.0.0
  package_info_plus: ^9.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  photo_view: ^0.15.0
  rss_dart: ^1.0.13
  shared_preferences: ^2.3.2
  shelf: ^1.4.1
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  webview_flutter: ^4.8.0
  xml: ^6.5.0
dev_dependencies:
  alchemist: ^0.12.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.4
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/manuals/
    - assets/manuals/explore/
    - assets/renderer/
#    - assets/samples/
